### ISSUE TITLE
snip

### ISSUE THREAD

**Issue by VaasKahnGrim** [MerryMaw/gearfox#1]
snip

**Comment by biorisk2** [comment]
maw sucks peen

**Comment by biorisk2** [comment]
maw should make a wikie 🤔

**Comment by MerryMaw** [comment]
Gearfox provides extra functionalities and conveniences that helps developers do more in their gamemodes by using stuff like resource.AddDir or AddLuaCSFolder, which adds entire folders instead of writting a quite long list of single file additions. 

To start off with, I would suggest reading the init.lua, shared.lua and cl_init.lua of Winter Survival 2 gamemode, also posted on my github, for an example implementation of GearFox. 

I will work on a wiki on Gearfox in the future when I have time. Thank you.
